version: "3.8"

services:
  mlflow:
    image: python:3.10-slim
    command: >
      bash -c "pip install mlflow && mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns"
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlruns

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MODEL_NAME=FraudDetectionModel
    depends_on:
      - mlflow
    volumes:
      - mlflow_data:/app/mlruns

volumes:
  mlflow_data:
